[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.4.1",
    "ipython>=8.27.0",
    "polars>=1.8.2",
]

[tool.ruff]
line-length = 80
