# ; Raw inputs
#
# (input fact Seq
#   (.sample Str) (.at Int) (.data Str))
#
# (input fact ReferenceGenome
#   (.data Str))

[Prop.Seq]
params.sample = "Str"
params.at = "Int"
params.data = "Str"


[Prop.ReferenceGenome]
params.data = "Str"

# ; Datatypes
#
# (output fact Reference
#   (.data Str))
#
# (output fact Alignment
#   (.sample Str) (.at Int))
#
# (output fact ReadCounts
#   (.sample Str) (.at Int))
#
# (output fact ReadCountMatrix
#   (.sample1 Str) (.sample2 Str) (.at Int) (.bc Int))
#
# (output fact DifferentialGeneExpression
#   (.sample1 Str) (.sample2 Str) (.at Int))

[Type.Reference]
params.data = "Str"

[Type.Alignment]
params.sample = "Str"
params.at = "Int"

[Type.ReadCounts]
params.sample = "Str"
params.at = "Int"

[Type.ReadCountMatrix]
params.sample1 = "Str"
params.sample2 = "Str"
params.at = "Int"
params.bc = "Int"

[Type.DifferentialGeneExpression]
params.sample1 = "Str"
params.sample2 = "Str"
params.at = "Int"

# ; Load reference genome
#
# (computation load_local_reference_genome Reference
#   ((rg ReferenceGenome))
#   ((= (.data ret) (.data rg))))
#
# (computation load_hg38 Reference () ())

[Function.load_local_reference_genome]
params.rg = "ReferenceGenome"
ret = "Reference"
condition = [
    "ret.data == rg.data",
]

[Function.load_hg_38]
params = []
ret = "ReferenceGenome"
condition = []

# ; Quantifiers
#
# (computation kallisto ReadCounts
#   ((seq Seq) (ref Reference))
#   ((= (.sample ret) (.sample seq))
#    (= (.at ret) (.at seq))))
#
# (computation salmon ReadCounts
#   ((seq Seq) (ref Reference))
#   ((= (.sample ret) (.sample seq))
#    (= (.at ret) (.at seq))))

[Function.kallisto]
params.seq = "Seq"
params.ref = "Reference"
ret = "ReadCounts"
condition = [
    "ret.sample = seq.sample",
    "ret.at = seq.at",
]

[Function.salmon]
params.seq = "Seq"
params.ref = "Reference"
ret = "ReadCounts"
condition = [
    "ret.sample = seq.sample",
    "ret.at = seq.at",
]

# ; Aligners
#
# (computation bowtie2 Alignment
#   ((seq Seq) (ref Reference))
#   ((= (.sample ret) (.sample seq))
#    (= (.at ret) (.at seq))))
#
# (computation star Alignment
#   ((seq Seq) (ref Reference))
#   ((= (.sample ret) (.sample seq))
#    (= (.at ret) (.at seq))))

[Function.bowtie2]
params.seq = "Seq"
params.ref = "Reference"
ret = "Alignment"
condition = [
    "ret.sample = seq.sample",
    "ret.at = seq.at",
]

[Function.star]
params.seq = "Seq"
params.ref = "Reference"
ret = "Alignment"
condition = [
    "ret.sample = seq.sample",
    "ret.at = seq.at",
]

# ; Read summarization
#
# (computation featureCounts ReadCounts
#   ((a Alignment))
#   ((= (.sample ret) (.sample a))
#    (= (.at ret) (.at a))))

[Function.featureCounts]
params.a = "Alignment"
ret = "ReadCounts"
condition = [
    "ret.sample = a.sample",
    "ret.at = a.at",
]

# ; Combine reads
#
# (computation combine_reads ReadCountMatrix
#   ((r1 ReadCounts) (r2 ReadCounts))
#   ((= (.sample1 ret) (.sample r1))
#    (= (.sample2 ret) (.sample r2))
#    (= (.at ret) (.at r1))
#    (= (.at r1) (.at r2))
#    (= (.bc ret) 0)))

[Function.combine_reads]
params.r1 = "ReadCounts"
params.r2 = "ReadCounts"
ret = "ReadCountMatrix"
condition = [
    "ret.sample1 = r1.sample",
    "ret.sample2 = r2.sample",
    "ret.at = r1.at",
    "ret.at = r2.at",
    "ret.bc = 0"
]

# ; Batch correction
#
# (computation combat_seq ReadCountMatrix
#   ((rcm ReadCountMatrix))
#   ((= (.sample1 ret) (.sample1 rcm))
#    (= (.sample2 ret) (.sample2 rcm))
#    (= (.at ret) (.at rcm))
#    (= (.bc rcm) 0)
#    (= (.bc ret) 1)))

[Function.combat_seq]
params.rcm = "ReadCountMatrix"
ret = "ReadCountMatrix"
condition = [
    "ret.sample1 = rcm.sample1",
    "ret.sample2 = rcm.sample2",
    "ret.at = rcm.at",
    "rcm.bc = 0",
    "ret.bc = 1",
]

# ; Differential gene expression
#
# (computation deseq2 DifferentialGeneExpression
#   ((rcm ReadCountMatrix))
#   ((= (.sample1 ret) (.sample1 rcm))
#    (= (.sample2 ret) (.sample2 rcm))
#    (= (.at ret) (.at rcm))))

[Function.deseq2]
params.rcm = "ReadCountMatrix"
ret = "DifferentialGeneExpression"
condition = [
    "ret.sample1 = rcm.sample1",
    "ret.sample2 = rcm.sample2",
    "ret.at = rcm.at",
]

# ; Pooled CRISPR screen
#
# (input fact Transfection
#   (.sample Str) (.at Int) (.library Str))
#
# (output fact Enrichment
#   (.sample Str) (.start Int) (.end Int))

[Prop.Transfection]
params.sample = "Str"
params.at = "Int"
params.library = "Str"

[Type.Enrichment]
name = "Enrichment"
params.sample = "Str"
params.start = "Int"
params.end = "Int"

# (computation reference_from_transfection Reference
#   ((t Transfection))
#   ((= (.data ret) (.library t))))

[Function.reference_from_transfection]
params.t = "Transfection"
ret = "Reference"
condition = [
    "ret.data = t.library",
]

# (computation mageck Enrichment
#   ((t Transfection) (s1 Seq) (s2 Seq))
#   ((= (.sample ret) (.sample t))
#    (= (.start ret) (.at s1))
#    (= (.end ret) (.at s2))
#    (= (.sample t) (.sample s1))
#    (= (.sample t) (.sample s2))
#    (< (.at t) (.at s1))
#    (< (.at s1) (.at s2))))
#
# (computation l2fc Enrichment
#   ((r1 ReadCounts) (r2 ReadCounts))
#   ((= (.start ret) (.at r1))
#    (= (.end ret) (.at r2))
#    (= (.sample ret) (.sample r1))
#    (= (.sample ret) (.sample r2))
#    (< (.at r1) (.at r2))))

[Function.mageck]
params.t = "Transfection"
params.s1 = "Seq"
params.s2 = "Seq"
ret = "Enrichment"
condition = [
    "ret.sample = t.sample",
    "ret.start = s1.at",
    "ret.end = s2.at",
    "t.sample = s1.sample",
    "t.sample = s2.sample",
    "t.at < s1.at",
    "s1.at < s2.at",
]

[Function.l2fc]
params.r1 = "ReadCounts"
params.r2 = "ReadCounts"
ret = "Enrichment"
condition = [
    "ret.start = r1.at",
    "ret.end = r2.at",
    "ret.sample = r1.sample",
    "ret.sample = r2.sample",
    "r1.at < r2.at",
]
