[[Fact]]
name = "ReferenceGenome"
args.data = "hg38.fasta"

[[Fact]]
name = "Seq"
args.sample = "Healthy"
args.at = 5
args.data = "healthy.fastq"

[[Fact]]
name = "Seq"
args.sample = "TLE"
args.at = 5
args.data = "tle.fastq"

[Goal]
name = "DifferentialGeneExpression"
args.sample1 = "Healthy"
args.sample2 = "TLE"
args.at = 5
