[[Prop]]
name = "ReferenceGenomeFile"
args.filename = "hg38.fasta"

[[Prop]]
name = "SeqFile"
args.sample = "Healthy"
args.at = 5
args.filename = "healthy.fastq"

[[Prop]]
name = "SeqFile"
args.sample = "TLE"
args.at = 5
args.filename = "tle.fastq"

[Goal]
name = "ReadCounts"
args.sample = "TLE"
args.at = 5

# [Goal]
# name = "DifferentialGeneExpression"
# args.sample1 = "Healthy"
# args.sample2 = "TLE"
# args.at = 5
