[[Prop]]
name = "ReferenceGenomeFile"
args = {}

[[Prop]]
name = "Seq"
args.sample = "Healthy"
args.at = 5
# args.data = "healthy.fastq"

[[Prop]]
name = "Seq"
args.sample = "TLE"
args.at = 5
# args.data = "tle.fastq"

[Goal]
name = "ReadCounts"
args.sample = "TLE"
args.at = 5

# [Goal]
# name = "DifferentialGeneExpression"
# args.sample1 = "Healthy"
# args.sample2 = "TLE"
# args.at = 5
