[package]
name = "honeybee-py"
version = "0.7.0"
authors = ["Justin Lubin <justin@jlubin.net>"]
description = "Honeybee Engine Python Bindings"
edition = "2021"
readme = "README.md"
repository = "https://github.com/justinlubin/honeybee"
license = "BSD-3-Clause"

[dependencies]
honeybee = { path = "../engine" }
pythonize = "0.29.0"
pbn = "0.3"

[dependencies.pyo3]
version = "0.29.0"
features = ["abi3-py38"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true

[lints.clippy]
new_without_default = "allow"
