[project]
name = "honeybee-library-generator"
version = "0.1.0"
description = "Define Honeybee libraries using Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "multiqc>=1.30",
    "polars>=1.33.0",
]

[tool.uv]
dev-dependencies = [
    "ipython>=9.2.0",
]
