[[Prop]]
name = "In"
args.x = 1

[[Prop]]
name = "In"
args.x = 2

[[Prop]]
name = "In"
args.x = 3

[[Prop]]
name = "In"
args.x = 4

[[Prop]]
name = "In"
args.x = 5

[[Prop]]
name = "In"
args.x = 6

[[Prop]]
name = "In"
args.x = 7

[[Prop]]
name = "In"
args.x = 8

[[Prop]]
name = "In"
args.x = 9

[[Prop]]
name = "In"
args.x = 10

[Goal]
name = "DepthSorted"
args = {}
