[[Prop]]
name = "RNAseq"
args.sample = "Healthy"
args.path = "raw_data/healthy/"

[[Prop]]
name = "RNAseq"
args.sample = "TLE"
args.path = "raw_data/tle/"

[Goal]
name = "DifferentialGeneExpression"
args.sample1 = "Healthy"
args.sample2 = "TLE"
