[Prop.RNASeq]
params.label = "Str"
params.sample_sheet = "Str"
params.raw_data = "Str"
info.overview = "RNA-seq"
info.params.label = "Label for data"
info.params.sample_sheet = "Path to sample sheet CSV"
info.params.raw_data = "Path to raw FASTQ files"

[Type.RNASeqDataset]
params.label = "Str"
params.sample_sheet = "Str"
params.path = "Str"
params.qc = "Bool"
info.overview = "Quality-checked RNA-seq data"
info.params.label = "Label for data"
info.params.sample_sheet = "Path to sample sheet CSV"
info.params.path = "Path to data ('^' represents output)"
info.params.qc = "Whether or not quality checks have been run"
info.suggested_variable_name = "rna_seq_data"

[Function.load_rna_seq]
ret = "RNASeqDataset"
condition = [
    "RNASeq { label = ret.label, sample_sheet = ret.sample_sheet, raw_data = ret.path }",
    "ret.qc = False",
]
info.overview = "Load RNA-seq dataset"

[Type.TranscriptMatrices]
params.label = "Str"
params.sample_sheet = "Str"
params.path = "Str"
info.overview = "Transcript-by-sample matrices of counts and abundance (TPM)"
info.params.label = "Label for data"
info.params.sample_sheet = "Path to sample sheet CSV"
info.params.path = "Path to data ('^' represents output)"
info.suggested_variable_name = "read_counts"

[Function.fastqc]
params.data = "RNASeqDataset"
ret = "RNASeqDataset"
condition = [
    "data.qc = False",
    "ret.label = data.label",
    "ret.sample_sheet = data.sample_sheet",
    "ret.path = data.path",
    "ret.qc = True",
]
info.overview = "Quality-check RNA-seq data (FastQC)"

[Function.cutadapt_illumina]
params.data = "RNASeqDataset"
ret = "RNASeqDataset"
condition = [
    "data.qc = True",
    "ret.label = data.label",
    "ret.sample_sheet = data.sample_sheet",
    "ret.path = "^trimmed"",
    "ret.qc = False",
]
info.overview = "Remove Illumina universal adaptor and poly-A tails (cutadapt)"

[Function.kallisto]
params.data = "RNASeqDataset"
ret = "TranscriptMatrices"
condition = [
    "ret.label = data.label",
    "ret.sample_sheet = data.sample_sheet",
    "ret.path = "^quant"",
]
info.overview = "Quantify transcript abundances (kallisto)"

