[Prop.RNASeqProp]
params.label = "Str"
params.sample_sheet = "Str"
params.raw_data = "Str"
info.overview = "RNA-seq"
info.params.label = "Label for data"
info.params.sample_sheet = "Path to sample sheet CSV"
info.params.raw_data = "Path to raw FASTQ files"

[Type.RNASeq]
params.label = "Str"
params.sample_sheet = "Str"
params.raw_data = "Str"
info.params.label = "Label for data"
info.params.sample_sheet = "Path to sample sheet CSV"
info.params.raw_data = "Path to raw FASTQ files"

[Function.reify_rna_seq]
params = {}
ret = "RNASeq"
condition = [
    "RNASeqProp { label = ret.label, sample_sheet = ret.sample_sheet, raw_data = ret.raw_data }",
]

[Type.RNASeqData]
params.label = "Str"
params.qc = "Bool"
info.params.label = "Label for data"
info.params.qc = "Whether or not quality checks have been run"

[Function.load_rna_seq_data]
params.rna_seq = "RNASeq"
ret = "RNASeqData"
condition = [
    "ret.label = rna_seq.label",
    "ret.qc = false",
]
info.overview = "Load RNA-seq dataset"

[Type.TranscriptMatrices]
params.label = "Str"
info.params.label = "Label for RNA-seq data to analyze"

[Function.fastqc]
params.data = "RNASeqData"
ret = "RNASeqData"
condition = [
    "data.qc = false",
    "ret.label = data.label",
    "ret.qc = true",
]
info.overview = "Quality-check RNA-seq data (FastQC)"

[Function.cutadapt_illumina]
params.data = "RNASeqData"
ret = "RNASeqData"
condition = [
    "data.qc = true",
    "ret.label = data.label",
    "ret.qc = false",
]
info.overview = "Remove Illumina universal adaptor and poly-A tails (cutadapt)"

[Function.kallisto]
params.data = "RNASeqData"
ret = "TranscriptMatrices"
condition = [
    "data.qc = true",
    "ret.label = data.label",
]
info.overview = "Quantify transcript abundances (kallisto)"

