name: Backend Tests

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "backend/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build backend
      working-directory: ./backend
      run: cargo build --verbose
    - name: Run backend tests
      working-directory: ./backend
      run: cargo test --verbose
