(facts
  (Resolution (.val 30))
  (Resolution (.val 90))
  (CRS (.val "EPSG:32610"))
  (CRS (.val "EPSG:26943"))
  (ResamplingMethod (.val "bilinear"))

  (InputRaster
    (.name "Landsat Scene")
    (.data "LC09_L1TP_044034_20240508_20240508_02_T1.tif")
    (.resolution 30)
    (.crs "EPSG:32610")
    (.bands 11)
    (.sensor "landsat-9")))

(goal
  (Raster
    (.name "Landsat NDVI")
    (.resolution 90)
    (.crs "EPSG:26943")
    (.bands 1)))
