[[Prop]]
name = "ResolutionChoice"
args.val = 10


[[Prop]]
name = "CRSChoice"
args.val = "EPSG:26943"

[[Prop]]
name = "CRSChoice"
args.val = "EPSG:4326"

[[Prop]]
name = "InputRaster"
args.name = "NED 10m DEM"
args.data = "ned10.tif"
args.resolution = 10
args.crs = "EPSG:32610"
args.bands = 1
args.sensor = "unknown"

[[Prop]]
name = "InputVector"
args.name = "Conterminous United States (CONUS)"
args.data = "conus.geojson"
args.crs = "EPSG:4326"

[Goal]
name = "Raster"
args.name = "Clipped DEM"
args.resolution = 10
args.crs = "EPSG:26943"
args.bands = 1
